resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: LoadBalancer

elasticsearchHosts: "https://elasticsearch-master:9200"

elasticsearchCertificateSecret: elasticsearch-master-certs
elasticsearchCertificateAuthoritiesFile: ca.crt

elasticsearchCredentialSecret: elasticsearch-master-credentials